### ISSUE TITLE
IOError: [Errno 121] Remote I/O error

### ISSUE THREAD

**Issue by DarKOrange75** [pcfens/RaspberryPi-AS3935#29]
Hi, 

I can't get it to work, I am running it it with a raspberry A+ and as soon as I test it with a piezo I get this error:

Traceback (most recent call last):
  File "demo.py", line 23, in handle_interrupt
    reason = sensor.get_interrupt()
  File "/home/pi/RaspberryPi-AS3935/RPi_AS3935/RPi_AS3935.py", line 48, in get_interrupt
    self.read_data()
  File "/home/pi/RaspberryPi-AS3935/RPi_AS3935/RPi_AS3935.py", line 234, in read_data
    self.registers = self.i2cbus.read_i2c_block_data(self.address, 0x00)
IOError: [Errno 121] Remote I/O error

Thank you for your help !

**Comment by pcfens** [comment]
Did you remember to enable the I2C device driver?

You may also need to set the [I2C bus to 1](https://github.com/pcfens/RaspberryPi-AS3935/blob/master/demo.py#L10-L13).

**Comment by DarKOrange75** [comment]
Thank you for your answer, I2C bus was set to 1, the AS3935 is detected with i2cdetect -y 1 in position 3
What do you mean by enable the I2C device driver?

     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          03 -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- 36 -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --

**Comment by pcfens** [comment]
By driver I mean the kernel module - that i2cdetect works makes me think it's working as expected.

Can you try running the python script as root (or using sudo)? I doubt that's it, but it'd be good to confirm.

**Comment by pawelKapl** [comment]
Same here, i2c is detecting module as 03 on bus 1. And getting very same error, with sudo too. Running on Raspberry Pi 2b.

**Comment by DarKOrange75** [comment]
Same error when running the script with sudo.

**Comment by zanzeoo** [comment]
same 

 File "demo.py", line 17, in <module>
    sensor.calibrate(tun_cap=0x0F)
  File "/home/pi/RaspberryPi-AS3935/RPi_AS3935/RPi_AS3935.py", line 24, in calibrate
    self.set_byte(0x08, (self.registers[0x08] & 0xF0) | tun_cap)
  File "/home/pi/RaspberryPi-AS3935/RPi_AS3935/RPi_AS3935.py", line 222, in set_byte
    self.i2cbus.write_byte_data(self.address, register, value)
IOError: [Errno 121] Remote I/O error

**Comment by pawelKapl** [comment]
Hey guys i noticed something interesting. Sensor is actually starting working when GND of Raspberry or sensor ground is connected to earth, or u just touch it with a finger. This might explain why for example sensor can work with LAN cable, but not on wifi.

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
I had the same issue when running the script.  I resolved it by changing the device address.  i2cdetect showed as follows:

`    0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          03 -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                         
`

So I changed the address to:

`sensor = RPi_AS3935(address=0x03, bus=1)`

I hope this helps someone else.
